### PR TITLE
1.2's packet and fix some error

### PR DESCRIPTION
**Pull request by nnnlog**
update for field in 1.2's packet

### CODE REVIEW

**Comment by Sandertv** [comment]
I'm not updating to 1.2 until it's fully released. I'm closing this as it needs more things to be updated once 1.2 is on the master branch of PMMP.

**Comment by Sandertv** [comment]
Actually, I'll keep it open until then.

**Comment by TheDiamondYT1** [comment]
1.2 is bae

**Comment by Sandertv** [comment]
Mixed return types don't exist, please use the ?Living nullable return type.

**Comment by TheDiamondYT1** [comment]
@Sandertv I waa gonna do that -_-

**Pull request merged**
